const ERR = {
  UNKNOWN_TYPE:    "UNKNOWN_TYPE",
  MISSING_SIG:     "MISSING_SIG",
  INVALID_SIG:     "INVALID_SIG",
  UNKNOWN_PEER_KEY:"UNKNOWN_PEER_KEY",
  BAD_PAYLOAD:     "BAD_PAYLOAD",
  BAD_TIMESTAMP:   "BAD_TIMESTAMP",
  PAYLOAD_TOO_LARGE:"PAYLOAD_TOO_LARGE",
  USER_NOT_FOUND:  "USER_NOT_FOUND",
  FORBIDDEN:       "FORBIDDEN",
  RATE_LIMIT:      "RATE_LIMIT",
  TIMEOUT:         "TIMEOUT",
  BAD_FROM:        "BAD_FROM",
  BAD_URL:         "BAD_URL",
  BAD_PUBKEY:      "BAD_PUBKEY",
};
module.exports = { ERR };
